version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - api

  api:
    image: clue/json-server
    ports:
      - "3001:80"
    volumes:
      - ./api-mock/db.json:/data/db.json
